# Generated by Django 2.2.3 on 2019-07-28 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extension', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('portrait', models.ImageField(null=True, upload_to='')),
                ('phone', models.CharField(max_length=12, null=True)),
                ('personal_info', models.TextField(max_length=150, null=True)),
            ],
        ),
    ]
