# Generated by Django 2.2.3 on 2019-07-28 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190728_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='id',
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extension', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
