# Generated by Django 2.2.3 on 2019-07-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190727_1915'),
        ('blog', '0002_auto_20190728_1543'),
    ]

    operations = [
    ]
