# Generated by Django 2.2.3 on 2019-07-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('content', models.TextField()),
                ('index', models.IntegerField()),
                ('star', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Subject')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaching_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_page', models.ImageField(null=True, upload_to='')),
                ('filename', models.TextField()),
                ('index', models.IntegerField()),
                ('star', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Subject')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
