# Generated by Django 2.2.3 on 2019-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190729_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='plan_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slide_count',
            field=models.IntegerField(null=True),
        ),
    ]
